pipeline {
    agent any

    tools {
        jdk 'java-11'
        maven 'maven'
    }

    stages{
        stage('git-checkout'){
            steps{
                git branch: 'main', url: 'https://github.com/ManojKRISHNAPPA/test-1.git'
            }
        }
        stage('Compile'){
            steps{
                sh "mvn compile"
            }
        }
        stage('Build'){
            steps{
                sh "mvn clean install"
            }
        }
        stage('Build and tag'){
            steps{
                sh "docker build -t manojkrishnappa/test:1 ."
            }
        }
        stage('containersation'){
            steps{
                sh '''
                    docker run -it -d --name c1 -p 9001:8080 manojkrishnappa/test:1
                ''' 
            }
        }
    }
}
